db:
  host: localhost # tools.db.svc.eqiad.wmflabs
  name: s54021__retractionbot

template_name_map:
  en: 
    Retracted: Retracted
    retraction: Retracted
    eoc: Expression of Concern
    erratum: Erratum
  fr:
    Retracted: Rétracté
    retraction: Rétracté
    eoc: Expression de réserves
    erratum: Erratum

template_field_names:
  en: 
    doi: doi
    pmid: pmid
    intentional: intentional
  fr: 
    doi: doi
    pmid: pmid
    intentional: intentionnel

summary_map:
  en: Flagging sources with dois highlighted by RetractionWatch
  fr: Mise en évidence de sources épinglées par [[Retraction Watch]]
